// pub mod duo_stats;
pub mod help;
pub mod leaderboard;
pub mod mob_stats;
pub mod player_names;
pub mod player_stats;
pub mod ranks;
pub mod replays;
pub mod rta_core;
pub mod shared;
pub mod suggestion;
pub mod upload_json;
// pub mod how_to_build;
pub mod best_pve_teams;
pub mod meta;
pub mod register;
pub mod services;
pub mod support;
